# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: shows-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: shows
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432

  db-test:
    container_name: shows-db-test
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: shows-test
      POSTGRES_USER: admin-test
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
