# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: shows-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: shows
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
